application: finalurl
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /
  static_files: static/index.html
  upload: static/index.html


- url: .*
  script: main.py

